### ISSUE TITLE
Damage Log compatibility request

### ISSUE THREAD

**Issue by cs96and** [ShoyuVanilla/FoundryVTT-Chat-Portrait#67]
I notice some of your CSS selectors use the `#chat-log` ID.  Would you consider removing this ID from the selectors please?  I believe the classes you are also using should be enough to correctly identify messages.

The reason I ask is because the next version of Damage Log (v1.3.0 - [currently available as a beta](https://github.com/cs96and/FoundryVTT-damage-log/releases/tag/1.3.0-beta)) will move all damage messages into their own list (ID: `#damage-log`), so your selectors will no longer catch them.

I've put a workaround for one of the selectors into the beta, but it would be nice if I didn't need to do this...

```css
/* Styling for chat portraits in the damage log tab */
#damage-log .message .message-header img
{
  flex: 0 0 0px;
  margin-right: 5px;
  margin-bottom: 3px;
  object-fit: cover;
}
```
